# _config.yml
title: "Himon's Personal Website"
subtitle: "Things I did, things I like now, and things I'm looking forward to"
name: "Himon Thakur"
description: "Himon's Personal Website"
url: "https://himonthakur.github.io"
repository: "himonthakur/himonthakur.github.io"
locale: "en-US"

atom_feed:
  hide: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Author Profile
author:
  name: "Himon Thakur"
  avatar: "/assets/images/profile.jpg"
  bio: "CSCI-MS @ UCCS || GTA, TA, CS Student Staff || agentic AI, RL, multimodal"
  location: "Colorado Springs, CO"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hthakur@uccs.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/himonthakur"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/himonthakur"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=_4UA7RsAAAAJ&hl=en"

# Theme Settings
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"