# _config.yml
title: "Himon's Website"
subtitle: "About me, things I like, and what I am or was up to."
name: "Himon Thakur"
description: "Himon's Website"
url: "https://himonthakur.github.io"
repository: "himonthakur/himonthakur.github.io"
locale: "en-US"

include: ["_pages", "_posts"]

atom_feed:
  hide: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Author Profile
author:
  name: "Himon Thakur"
  avatar: "/assets/images/profile.jpg"
  bio: "Finishing up my CS master's at UCCS. Planning to join a PhD in Fall '26."


# Theme Settings
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"